INSERT INTO `provinces`
(1,1, 'أدرار', 'Adrar', NULL, NULL),
(2,2, 'الشلف', 'Chlef', NULL, NULL),
(3,3, 'الأغواط', 'Laghouat', NULL, NULL),
(4,4, 'أم البواقي', 'Oum El Bouaghi', NULL, NULL),
(5,5, 'باتنة', 'Batna', NULL, NULL),
(6,6, 'بجاية', 'Béjaïa', NULL, NULL),
(7,7, 'بسكرة', 'Biskra', NULL, NULL),
(8,8, 'بشار', 'Béchar', NULL, NULL),
(9,9, 'البليدة', 'Blida', NULL, NULL),
(10,10, 'البويرة', 'Bouira', NULL, NULL),
(11,11, 'تمنراست', 'Tamanrasset', NULL, NULL),
(12,12, 'تبسة', 'Tébessa', NULL, NULL),
(13,13, 'تلمسان', 'Tlemcen', NULL, NULL),
(14,14, 'تيارت', 'Tiaret', NULL, NULL),
(15,15, 'تيزي وزو', 'Tizi Ouzou', NULL, NULL),
(16,16, 'الجزائر', 'Alger', NULL, NULL),
(17,17, 'الجلفة', 'Djelfa', NULL, NULL),
(18,18, 'جيجل', 'Jijel', NULL, NULL),
(19,19, 'سطيف', 'Sétif', NULL, NULL),
(20,20, 'سعيدة', 'Saïda', NULL, NULL),
(21,21, 'سكيكدة', 'Skikda', NULL, NULL),
(22,22, 'سيدي بلعباس', 'Sidi Bel Abbès', NULL, NULL),
(23,23, 'عنابة', 'Annaba', NULL, NULL),
(24,24, 'قالمة', 'Guelma', NULL, NULL),
(25,25, 'قسنطينة', 'Constantine', NULL, NULL),
(26,26, 'المدية', 'Médéa', NULL, NULL),
(27,27, 'مستغانم', 'Mostaganem', NULL, NULL),
(28,28, 'المسيلة', 'M\'Sila', NULL, NULL),
(29,29, 'معسكر	', 'Mascara', NULL, NULL),
(30,30, 'ورقلة', 'Ouargla', NULL, NULL),
(31,31, 'وهران	', 'Oran', NULL, NULL),
(32,32, 'البيض', 'El Bayadh', NULL, NULL),
(33,33, 'اليزي', 'Illizi', NULL, NULL),
(34,34, 'برج بوعريريج', 'Bordj Bou Arreridj', NULL, NULL),
(35,35, 'بومرداس', 'Boumerdès', NULL, NULL),
(36,36, 'الطارف', 'El Tarf', NULL, NULL),
(37,37, 'تندوف', 'Tindouf', NULL, NULL),
(38,38, 'تسمسيلت', 'Tissemsilt', NULL, NULL),
(39,39, 'الوادي', 'El Oued', NULL, NULL),
(40,40, 'خنشلة', 'Khenchela', NULL, NULL),
(41,41, 'سوق أهراس', 'Souk Ahras', NULL, NULL),
(42,42, 'تيبازة', 'Tipaza', NULL, NULL),
(43,43, 'ميلة', 'Mila', NULL, NULL),
(44,44, 'عين الدفلى	', 'Aïn Defla', NULL, NULL),
(45,45, 'النعامة', 'Naâma', NULL, NULL),
(46,46, 'عين تموشنت', 'Aïn Témouchent', NULL, NULL),
(47,47, 'غرداية', 'Ghardaïa', NULL, NULL),
(48,48, 'غليزان', 'Relizane', NULL, NULL),
(49,49, 'المغير', 'El M\'ghair', NULL, NULL),
(50,50, 'المنيعة', 'El Menia', NULL, NULL),
(51,51, 'أولاد جلال', 'Ouled Djellal', NULL, NULL),
(52,52, 'برج باجي مختار', 'Bordj Baji Mokhtar', NULL, NULL),
(53,53, 'بني عباس', 'Béni Abbès', NULL, NULL),
(54,54, 'تيميمون', 'Timimoun', NULL, NULL),
(55,55, 'تقرت', 'Touggourt', NULL, NULL),
(56,56, 'جانت', 'Djanet', NULL, NULL),
(57,57, 'عين صالح', 'In Salah', NULL, NULL),
(58,58, 'عين قزام', 'In Guezzam', NULL, NULL);
